source 'https://github.com/CocoaPods/Specs.git'
project './Sample.xcodeproj'
platform :ios, '9.0'

use_frameworks!

inhibit_all_warnings!

pre_install do |installer|

end

# Abstract ==== ==============================

abstract_target 'All' do

    pod 'UIPreviewActivityViewController', :path => '../'

    post_install do |installer|

        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                if config.build_settings['SWIFT_VERSION'].nil? == false
                    config.build_settings['SWIFT_VERSION'] = '5'
                end
            end
        end

        installer.pods_project.build_configurations.each do |config|
            if !config.name.include?("Release")
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
            end
        end
    end

    target 'Sample' do
        # Nothing
    end

end
